version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres